### ISSUE TITLE
Unable to create using RS256

### ISSUE THREAD

**Issue by Mindless999** [anthonyg-1/PSJsonWebToken#2]
I am unable to create a key using RSA using this script. 
The Alg I am required to use is RS256. How would I be able to do that?

**Comment by anthonyg-1** [comment]
Can you share your code that isn't working as well as what operating system? Are you trying to create a JSON Web Token or JSON Web Key? If you're trying to create a RS256 signed JWT you'll need a PFX file. Here's how that's done (per the readme and comment-based help for New-JsonWebToken):

```powershell
# Create an RSA-SHA256 signed JWT with a five minute lifetime
$cert = Get-PfxCertificate -FilePath "~/certs/cert.pfx"
$jwt = New-JsonWebToken -Claims @{sub="username@company.com"} -HashAlgorithm SHA256 -Certificate $cert -TimeToLive 300
```

If you're trying to create a JWK (JSON Web Key) or JWK set, here's how that's done:
```powershell
# Certificate to be used for all examples below:
$cert = Get-PfxCertificate -FilePath "~/certs/cert.pfx"

# 1. Generate JWK set from certificate with thumbprint A80260EBE2E455429A702E9E6A0FD01C3F902C6B:
$cert | New-JsonWebKeySet

# 2. Generate JSON Web Key from certificate with thumbprint A80260EBE2E455429A702E9E6A0FD01C3F902C6B:
$cert | New-JsonWebKey

# 3. Generate JWK set from certificate with thumbprint A80260EBE2E455429A702E9E6A0FD01C3F902C6B and compress the output:
$cert | New-JsonWebKeySet -Compress

# Create an RSA-SHA256 signed JWT with a five minute lifetime
$cert = Get-PfxCertificate -FilePath "~/certs/cert.pfx"
```

**Comment by Mindless999** [comment]
It might be that I have misinterpreted the use of the JWK / JWT. For now it seems that we will be dropping this. Thank you for explaining
